WebAppMvcControllerViewLayout/Controllers/BasicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebAppMvcControllerViewLayout.Controllers
{
    public class ObjectComplex
    {
        public char character;
        public string name;
    }
    public class BasicController : Controller
    {
        //
        // GET: /Basic/

        public ActionResult Index()
        {
            return View();
        }

        public void Test()
        {

        }

        public ActionResult Helpers()
        {
            return View();
        }

        public ActionResult RequestQueryStringParam(int cod, string name)
        {
            ViewBag.cod = "RequestQueryStringParam: " + cod;
            ViewBag.name = "RequestQueryStringParam: " + name;
            return View();
        }

        public ActionResult RequestRouteParam(int id)
        {
            ViewBag.id = "RequestRouteParam: " + id;
            return View();
        }        

        public ActionResult PassingData()
        {
            ViewBag.ViewBagParam1 = "text raw";
            ViewData["ViewDataParam1"] = 1;

            TempData["TempDataParam1"] = 1.1;
            Session["SessionParam1"] = true;

            ViewBag.ObjectComplex = new ObjectComplex{ character = 'a', name = "Sam" };

            return View();
        }

        public ActionResult BundleSequence()
        {
            return View();
        }

        public string Calc(int v1, int v2)
        {
            return (v1 + v2).ToString();
        }



    }
}

WebAppMvcControllerViewLayout/Views/Basic/BundleSequence.cshtml
@{
    ViewBag.Title = "BundleSequence";
}

<h2>BundleSequence</h2>
Register in global.asax
<pre>public class MvcApplication : System.Web.HttpApplication{
    protected void Application_Start(){
        BundleConfig.RegisterBundles(BundleTable.Bundles);
    }
}</pre>

Add CSS and JS in \app_start\bundleconfig.cs
<pre>public class BundleConfig{
    public static void RegisterBundles(BundleCollection bundles){
            bundles.Add(new StyleBundle("~/Content/css").Include(
                    "~/Content/site.css"));
        
            bundles.Add(new ScriptBundle("~/bundles/jquery").Include(
                    "~/Scripts/jquery.js"));
    }
}</pre>
<hr />
Call in View
<pre>&#64;Styles.Render("~/Content/css")
&#64;Scripts.Render("~/bundles/jquery")
</pre>

WebAppMvcControllerViewLayout/Views/Basic/FinalDestiny.cshtml
@{
    ViewBag.Title = "FinalDestiny";
}

<h2>FinalDestiny</h2>
<p></p>
<pre>RedirectToAction("FinalDestiny");
RedirectToActionPermanent("Destiny");

Redirect("teste.aspx");
RedirectPermanent("teste.aspx");

RedirectToDestiny();

RedirectToRoute(new { id = 55 });
RedirectToRoutePermanent(new { id = 56 });
</pre>

source: http://www.exceptionnotfound.net/asp-net-mvc-demystified-actionresults/

WebAppMvcControllerViewLayout/Views/Basic/Helpers.cshtml
@{
    ViewBag.Title = "Helpers";
}
@section featured{
    <b>Text defined in View, but reserved in Layout.cshtml</b>
}

<h2>Helpers to Layout</h2>
<h3>Razor Helper link &#64;Html and &#64;Url</h3>
<pre>@@Html.ActionLink("link", "MethodName", "ControllerName") @Html.ActionLink("link", "MethodActionName", "ControllerName")
@@Html.ActionLink("link", "MethodActionName", new { id=5, name="sam" })  @Html.ActionLink("link", "MethodActionName", new { id=5, name="sam" }) (with param id and QueryString)
@@Html.ActionLink("link", "MethodActionName", new { code=5, name="sam" }) @Html.ActionLink("link", "MethodActionName", new { code=5, name="sam" }) (with QueryString)

&lt;a href="@@Html.Action("Test", "Basic")"&gt;link&lt;/a&gt; <a href="@Html.Action("Test", "Basic")">link</a> (with validation of resource existing)
&lt;a href="@@Url.Action("MethodActionNotExist", "ControllerNotExist")"&gt;link&lt;/a&gt; <a href="@Url.Action("MethodActionNotExist", "ControllerNotExist")">link</a>

@@Html.Raw("raw text") @Html.Raw("raw text")
@@Html.Raw("&lt;p&gt;paragraph&lt;/p&gt;") @Html.Raw("<p>paragraph</p>")
</pre>

<h3>Razor Helper Layout</h3>
<p>@@RenderPage()</p>
<pre>@@RenderPage("~/Views/_PartialAspNetMvc.cshtml") @RenderPage("~/Views/_PartialAspNetMvc.cshtml")
<hr />
<p>@@Html.Partial()</p>
@@Html.Partial("~/Views/_PartialAspNetMvc.cshtml") @Html.Partial("~/Views/_PartialAspNetMvc.cshtml")
<hr />
<p>@@{Html.RenderPartial();}</p>
@@{Html.RenderPartial("~/Views/_PartialAspNetMvc.cshtml");} @{Html.RenderPartial("~/Views/_PartialAspNetMvc.cshtml");}
<hr />
<p>@@{Html.RenderAction();}</p>
@@{Html.RenderAction("Calc", new { v1 = 1, v2 = 2 });} @{Html.RenderAction("Calc", new { v1 = 1, v2 = 2 });}
<hr />
<p>@@RenderSection()</p>
_Layout.cshtml
@@RenderSection("featured", required: false)

Index.cshtml
@@section featured{
 &lt;b&gt;Text defined in View, but reserved in Layout.cshtml&lt;/b&gt;
}
<hr />
<p>@@RenderBody() - ContentPlaceHolder </p>
_Layout.cshtml
&lt;html&gt;
 &lt;body&gt;
  &lt;div class="main"&gt;@@RenderBody()&lt;/div&gt;
 &lt;/body&gt;
&lt;/html&gt;

Index.cshtml<span style="color:red">
&lt;html&gt;
 &lt;body&gt;
  &lt;div class="main"&gt;</span>
   &lt;p&gt;Text in View&lt;/p&gt;
<span style="color:red">&lt;/div&gt;
 &lt;/body&gt;
&lt;/html&gt;</span>
<hr />
<p>@@Url.Content()</p>
&lt;link href="@@Url.Content("~/Content/style.css")" /&gt;
</pre>

WebAppMvcControllerViewLayout/Views/Basic/Index.cshtml
@{
    ViewBag.Title = "Index";
    string textInfo = "Today is: ";
}

<h2>C# in View</h2>
<h3>C# statements</h3>
<pre>&#64;{
    string textInfo = "Today is: ";
    string dateToday = DateTime.Now.ToString();
}
&#64;foreach (var item in collection){
        
}
&#64;if (true){
        
}
&#64;using (resource){
        
}</pre>

<h3>C# write variable and raw text: &lt;text&gt;raw text&lt;/text&gt; &#64;:raw text</h3>
<pre>Inline
@@textInfo @textInfo

Block
&#64;{
    &lt;text&gt;&#64;textInfo&lt;/text&gt; <text>@textInfo</text>
    &lt;text&gt;raw text&lt;/text&gt; <text>raw text</text>     

@{
    <text>&#64;:raw text</text> @:raw text
    <text>&#64;:&lt;p&gt;paragraph&lt;/p&gt;</text> @:<p>paragraph</p>
}
}</pre>

@Html.ActionLink("Helpers to Layout and Interaction", "Helpers") - 
@Html.ActionLink("Request QueryString Param", "RequestQueryStringParam", new{cod=66, name="Sam"}) - 
@Html.ActionLink("Request Route Param", "RequestRouteParam", new{id=55}) - 
@Html.ActionLink("Passing Data", "PassingData") - 
@Html.ActionLink("Bundle Sequence", "BundleSequence")

WebAppMvcControllerViewLayout/Views/Basic/PassingData.cshtml
@{    
    ViewBag.Title = "PassingData";
}

<h2>PassingData</h2>
<p>Controller</p>
<pre>public ActionResult PassingData(){
    ViewBag.ViewBagParam1 = "text raw";
    ViewData["ViewDataParam1"] = 1;
    TempData["TempDataParam1"] = 1.1;
    Session["SessionParam1"] = true;
    ViewBag.ObjectComplex = new ObjectComplex{ character = 'a', name = "Sam" };
}</pre>
<hr />
<p>View</p>
            
<p>@@ViewBag.ViewBagParam1 @ViewBag.ViewBagParam1</p>

<p>@@ViewData["ViewDataParam1"] @ViewData["ViewDataParam1"] ViewData ViewDataDictionary : IDictionary&lt;string, object&gt;</p>

<p>@@TempData["TempDataParam1"] @TempData["TempDataParam1"]</p>

<p>@@Session["SessionParam1"] @Session["SessionParam1"]</p>

<p>@@ViewBag.ObjectComplex.id  @ViewBag.ObjectComplex.character - @@ViewBag.ObjectComplex.name @ViewBag.ObjectComplex.name</p>

source: http://www.dotnet-tricks.com/Tutorial/mvc/9KHW190712-ViewData-vs-ViewBag-vs-TempData-vs-Session.html

WebAppMvcControllerViewLayout/Views/Basic/RequestQueryStringParam.cshtml
@{
    ViewBag.Title = "RequestQueryStringParam";
}

<h2>RequestQueryStringParam</h2>

<p>Request ActionLink</p>
<pre>@@Html.ActionLink("Request QueryString Param", "RequestQueryStringParam", new{cod=66, name="Sam"})</pre>

<hr />

<p>URL: querystring combine with params of controller</p>
<pre>.../RequestQueryStringParam?cod=66&name=sam</pre>

<hr />

<p>Controller</p>
<pre>public ActionResult RequestQueryStringParam(int cod, string name){
    ViewBag.cod = "RequestQueryStringParam: " + cod;
    ViewBag.name = "RequestQueryStringParam: " + name;
    return View();
}</pre>

<hr />

<p>View</p>

<p>@@ViewBag.cod @ViewBag.cod</p>

<p>@@ViewBag.name @ViewBag.name</p>

WebAppMvcControllerViewLayout/Views/Basic/RequestRouteParam.cshtml
@{
    ViewBag.Title = "RequestRouteParam";
}

<h2>RequestRouteParam</h2>

<p>Request ActionLink</p>
<pre>@@Html.ActionLink("Request QueryString Param", "RequestQueryStringParam", new{id=55})</pre>

<hr />

<p>URL: Action/param combine with param of controller and route registered in global.asax</p>
<pre>.../RequestRouteParam/55</pre>
Global.asax
<pre>public class MvcApplication : System.Web.HttpApplication {
    protected void Application_Start(){
        RouteConfig.RegisterRoutes(RouteTable.Routes);
    }
}</pre>
RouteConfig.cs
<pre>public class RouteConfig {
    public static void RegisterRoutes(RouteCollection routes) {
        routes.IgnoreRoute("{resource}.axd/{*pathInfo}");
        routes.MapRoute(
            name: "Default",
            url: "{controller}/{action}/{id}",
            defaults: new { controller = "Home", action = "Index", id = UrlParameter.Optional }
        );
    }
}</pre>

<hr />

<p>Controller</p>
<pre>public ActionResult RequestQueryStringParam(int id){
    ViewBag.id = "RequestRouteParam: " + id;
    return View();
}</pre>

<hr />

<p>View</p>

<p>@@ViewBag.id @ViewBag.id</p>

WebAppMvcControllerViewLayout/Views/Basic/rest.cshtml
@{
    ViewBag.Title = "rest";
}

<h2>rest</h2>

source: http://haacked.com/archive/2011/01/06/razor-syntax-quick-reference.aspx/<br />
    C#

<p>Some Helpers &#64;Html</p>
<ul>
    <li>ViewBag</li>
    <li>ViewData</li>
    <li>AntiForgeryToken() - Generates a hidden form field (anti-forgery token) that is validated when the form is submitted.</li>
    <li>AttributeEncode()</li>
    <li>EnableClientValidation()</li>
    <li>EnableUnobtrusiveJavaScript()</li>
    <li>Encode()</li>
    <li>FormatValue()</li>
    <li>GenerateIdFromName()</li>
    <li>GenerateLink()</li>
    <li>GenerateRouteLink()</li>
    <li>GetFormMethodString()</li>
    <li>GetInputTypeString()</li>
    <li>GetUnobtrusiveValidationAttributes()</li>
    <li>HttpMethodOverride(HttpVerbs)</li>
    <li>ObjectToDictionary(Object)</li>
    <li>Raw()</li>
    <li>SetValidationMessageElement()</li>
    <li>SetValidationSummaryMessageElement()</li>
</ul>
<p>Extensions</p>
<ul>
    <li>Action()</li>
    <li>ActionLink()</li>
    <li>BeginForm() EndForm()</li>
    <li>BeginRouteForm()</li>
    <li>CheckBox()</li>
    <li>DropDownList() ListBox()</li>
    <li>Editor() EditorForModel()</li>
    <li>Hidden()</li>
    <li>Label() LabelForModel()</li>
    <li>Password()</li>
    <li>RadioButton()</li>
    <li>TextArea()</li>
    <li>TextBox()</li>

    <li>Display() DisplayForModel() DisplayName() DisplayText()</li>
    <li>Id() IdForModel()</li>
    <li>Name() NameForModel()</li>
    <li>Partial()</li>
    <li>RenderAction()</li>
    <li>RenderPartial()</li>
    <li>RouteLink()</li>
    <li>Validate() ValidationMessage() ValidationSummary()</li>
    <li>Value() ValueForModel()</li>
</ul>
<p>source: https://msdn.microsoft.com/en-us/library/system.web.mvc.htmlhelper(v=vs.118).aspx</p>
<p>Some Helpers &#64;Page</p>@Page
<ul>
    <li>RenderBody()</li>
    <li>RenderPage()</li>
    <li>RenderSection()</li>
</ul>
<p>Helper &#64;Url.Action()</p>
    </li>
</ol>

@{
    //---statement or Code Block
    string text = "Today is: ";
    string today = DateTime.Now.ToString();
    <text>@text @today</text>
    @:text raw
}
@if (true)
{
    <text>ok</text>
}
<p>END</p>

http://www.asp.net/mvc/overview/older-versions-1/views/asp-net-mvc-views-overview-cs